const cities = [
    { country: 'United Kingdom',    city:'London   ', woeid:  44418            },
    { country: 'United States',     city:'Albany    ', woeid:  2352646          },
    { country: 'United States',     city:'Annapolis ', woeid:     2354877       },
    { country: 'United States',     city:'Atlanta   ', woeid:  2357024          },
    { country: 'United States',     city:'Augusta   ', woeid:  2357379          },
    { country: 'United States',     city:'Austin    ', woeid:  2357536          },
    { country: 'United States',     city:'Baton Roug', woeid: 	2359991          },
    { country: 'United States',     city:'Bismarck ', woeid:     2364681        },
    { country: 'United States',     city:'Boise '	  , woeid:     2366355       },
    { country: 'United States',     city:'Boston   ' , woeid:  2367105          },
    { country: 'United States',     city:'Charleston', woeid:	2378317          },
    { country: 'United States',     city:'Cheyenne ', woeid:     2379552        },
    { country: 'United States',     city:'Columbia ', woeid:     2383552        },
    { country: 'United States',     city:'Columbus ', woeid:     2383660        },
    { country: 'United States',     city:'Concord  ' , woeid:  2384019          },
    { country: 'United States',     city:'Denver   ', woeid:  2391279          },
    { country: 'United States',     city:'Des Moines', woeid:	2391446          },
    { country: 'United States',     city:'Dover 	'  , woeid:       2393370     },
    { country: 'United States',     city:'Frankfort ', woeid: 2406903           },
    { country: 'United States',     city:'Harrisburg', woeid:	2418046          },
    { country: 'United States',     city:'Hartford ', woeid: 2418244            },
    { country: 'United States',     city:'Helena   ' , woeid:  2419761          },
    { country: 'United States',     city:'Honolulu ', woeid: 2423945            },
    { country: 'United States',     city:'Indianapol', woeid:	   2427032       },
    { country: 'United States',     city:'Jackson   ', woeid:      2428184      },
    { country: 'United States',     city:'Jefferson ', woeid:    	2428866      },
    { country: 'United States',     city:'Juneau    ', woeid:      2430300      },
    { country: 'United States',     city:'Lansing   ', woeid:      2436453      },
    { country: 'United States',     city:'Lincoln   ', woeid:  	2439482      },
    { country: 'United States',     city:'Little Roc', woeid:  2440351          },
    { country: 'United States',     city:'Madison   ', woeid:      2443945      },
    { country: 'United States',     city:'Montgomery', woeid:	2453369          },
    { country: 'United States',     city:'Montpelier', woeid:	2453516          },
    { country: 'United States',     city:'Nashville ', woeid:  2457170          },
    { country: 'United States',     city:'Oklahoma City', woeid:	   2464592       },
    { country: 'United States',     city:'Olympia   ', woeid:      2465478      },
    { country: 'United States',     city:'Phoenix   ', woeid:      2471390      },
    { country: 'United States',     city:'Pierre    ', woeid:      2471666      },
    { country: 'United States',     city:'Providence', woeid:        	2477058  },
    { country: 'United States',     city:'Raleigh   ', woeid:      2478307      },
    { country: 'United States',     city:'Richmond  ', woeid:         2480894   },
    { country: 'United States',     city:'Sacramento', woeid:        	2486340  },
    { country: 'United States',     city:'Saint Paul', woeid:        	2487129  },
    { country: 'United States',     city:'Salem '	  , woeid:          2487384  },
    { country: 'United States',     city:'Salt Lake' , woeid:        	2487610  },
    { country: 'United States',     city:'Santa Fe ', woeid:      488867        },
    { country: 'United States',     city:'Springfiel', woeid:      2498306      },
    { country: 'United States',     city:'Tallahasse', woeid:      2503713      },
    { country: 'United States',     city:'Topeka    ', woeid:      2507158      },
    { country: 'United States',     city:'Trenton   ', woeid:      2507854      }
];

export default cities;